<a href="https://colab.research.google.com/github/JBSspc/PracticasComputacionII/blob/main/C2_Parcial1_spc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computación II**
Parcial 1 </br>
*Sofía Palacios Cuevas* </br>
MAR 28 2022

a) Diseña un programa en python para encriptar un mensaje utilizando una matriz invertible de 3x3, calcular su inversa y desencriptar el mensaje

Pasos:
* Llenar la matriz A
* Obtener la inversa A^-1
* Llenar la matriz M
* Mutilplicar (A)(M) para obtener E
* Multiplicar (A^-1)(E) para recuperar M


In [ ]:
# llenamos la matriz A
import numpy as np
import sys

# llenar la matriz
print('\n----- Entrada de valores para A -----\n')
v = int(input('n: '))
c = 2 * v
z = np.zeros((v,v))

print ('\nCoeficientes de la matriz aumentada: ')
for i in range(v):
  for j in range(v):
    z[i][j] = float(input('Valor del elemento [' + str(i) + '][' + str(j) + ']: '))
A = z
print(A)


----- Entrada de valores para A -----

n: 3

Coeficientes de la matriz aumentada: 
Valor del elemento [0][0]: -3
Valor del elemento [0][1]: -3
Valor del elemento [0][2]: -4
Valor del elemento [1][0]: 0
Valor del elemento [1][1]: 1
Valor del elemento [1][2]: 1
Valor del elemento [2][0]: 4
Valor del elemento [2][1]: 3
Valor del elemento [2][2]: 4
[[-3. -3. -4.]
 [ 0.  1.  1.]
 [ 4.  3.  4.]]


In [ ]:
# llenamos M
# llenar la matriz
print('\n----- Entrada de valores para M -----\n')
vp = v # v' es igual a v (dimensión de 3x3)
# c = 2 * vp
zp = np.zeros((vp,vp)) #z' tiene las mismas dimensiones de z

print ('\nCoeficientes de la matriz aumentada: ')
for i in range(vp):
  for j in range(vp):
    zp[i][j] = float(input('Valor del elemento [' + str(i) + '][' + str(j) + ']: '))
M = zp
print(M)

# Hacemos la multiplicación entre matrices y la asignamos a E
# E = (A)(M)

E = np.dot(A,M)
print('\nEncriptado:\n',E)


----- Entrada de valores para M -----


Coeficientes de la matriz aumentada: 
Valor del elemento [0][0]: 97
Valor del elemento [0][1]: 116
Valor del elemento [0][2]: 97
Valor del elemento [1][0]: 99
Valor del elemento [1][1]: 97
Valor del elemento [1][2]: 48
Valor del elemento [2][0]: 57
Valor del elemento [2][1]: 51
Valor del elemento [2][2]: 48
[[ 97. 116.  97.]
 [ 99.  97.  48.]
 [ 57.  51.  48.]]

Encriptado:
 [[-816. -843. -627.]
 [ 156.  148.   96.]
 [ 913.  959.  724.]]


In [ ]:
# obtenemos A^-1

# concatenamos A e I
I = np.identity(v)
zI = np.concatenate([z, I], axis = 1) # axis = 1 -> concatenar columnas
print('\nMatriz A e I concatenadas: \n', zI)

# redimensionamos 
f = len(zI)
s = 2 * len(zI) 
print('\nfilas de zI: ', f, '\ncolumnas de zI: ', s, '\n')

# Aplicamos Gauss-Jordan a la matriz concatenada
# Gauss (ceros debajo de la diagonal principal)
for i in range(f):
  if zI[i][j] == 0.0:
    sys.exit('Alto! Disión entre 0!')
  for j in range (f):
    if i != j:
      r = zI[j][i] / zI[i][i]
      for k in range(s):
        zI[j][k] = zI[j][k] - r * zI[i][k]

print('Aplicando eliminación Gaussiana (hacia abajo):\n', zI)

# Gauss Jordan (ceros arriba de la diagonal principal)
for i in range(f):
  p = zI[f-1-i][f-1-i]
  zI[f-1-i] = zI[f-1-i]/p
  for j in range(f-1-i):
    zI[j] = zI[j] - zI[j][f-1-i] * zI[f-1-i] 

print('\nAplicando GJ (hacia arriba):\n', zI)

# Separamos ambas matrices
# La matriz de la derecha será A^-1
I,AI = np.hsplit(zI,2)

# Corroboramos que se invirtió A correctamente
# Sí funcionó, por lo que comentaremos las siguientes líneas
# AdotAI = np.dot(A,AI)

# print('Matriz A:\n', A)
print('\nMatriz invertida A^-1:\n', AI)
# print('\nProducto AA^-1:\n', AdotAI)


Matriz A e I concatenadas: 
 [[-3. -3. -4.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.]
 [ 4.  3.  4.  0.  0.  1.]]

filas de zI:  3 
columnas de zI:  6 

Aplicando eliminación Gaussiana (hacia abajo):
 [[-3.00000000e+00  0.00000000e+00  0.00000000e+00 -3.00000000e+00
  -2.66453526e-15 -3.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  4.00000000e+00
   4.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.33333333e-01  1.33333333e+00
   1.00000000e+00  1.00000000e+00]]

Aplicando GJ (hacia arriba):
 [[ 1.0000000e+00 -0.0000000e+00 -0.0000000e+00  1.0000000e+00
   8.8817842e-16  1.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00  4.0000000e+00
   4.0000000e+00  3.0000000e+00]
 [-0.0000000e+00 -0.0000000e+00  1.0000000e+00 -4.0000000e+00
  -3.0000000e+00 -3.0000000e+00]]

Matriz invertida A^-1:
 [[ 1.0000000e+00  8.8817842e-16  1.0000000e+00]
 [ 4.0000000e+00  4.0000000e+00  3.0000000e+00]
 [-4.0000000e+00 -3.0000000e+00 -3.0000000e+00]]


In [ ]:
# Desencriptamos
D = np.dot(AI,E)

# Corroboramos que todo sea correcto

print('\nMensaje: \n', M, '\n')
print('\nEcriptado: \n', E, '\n')
print('\nDesencriptado: \n', D, '\n')


Mensaje: 
 [[ 97. 116.  97.]
 [ 99.  97.  48.]
 [ 57.  51.  48.]] 


Ecriptado: 
 [[-816. -843. -627.]
 [ 156.  148.   96.]
 [ 913.  959.  724.]] 


Desencriptado: 
 [[ 97. 116.  97.]
 [ 99.  97.  48.]
 [ 57.  51.  48.]] 



b) Se deberá utilizar el método de supreferencia para aproximar con una tolerancia de 0.000001 todas las raíces reales del siguiente polinomio </br>
x^4 - 4x^3 -2x^2 +12x - 5

In [ ]:
class NumMethods:
  def NewtonRaphsonUpperGrade(self, f, x, tol, maxIter ):
    for i in range(maxIter):
      c = x - ((f[0](x))*(f[1](x)))/(((f[1](x))**2)*(f[2](x))) # x - [f(x)f'(x)]/[(f'(x))^2 f''(x])
      if abs(c-x) < tol: break # altoo
      x = c # vamos 'rotando' el valor
    return c, i

def main():
  maxIter = 900000
  tol = 0.000001
  # f[0] = x**4 - 4*x**3 - 2*x**2 + 12*x - 5
  # f[1] = 4*x**3 - 12*x**2 - 4*x +12
  # f[2] = 12*x**2 - 24*x -4
   # hacemos una lista de funciones derivadas
  f = [lambda x: x**4 - 4*x**3 - 2*x**2 + 12*x - 5, lambda x: 4*x**3 - 12*x**2 - 4*x +12, lambda x: 12*x**2 - 24*x -4 ]

  objN = NumMethods() # Objeto 'objN' de NumMethods
  x0,n0 = objN.NewtonRaphsonUpperGrade(f,5, tol, maxIter) # Aplicamos la función
  
  # Raíz 1
  if (x0 != np.inf): # que no sea oo
    print('X0 = %f alcanzada en %d iteraciones :D' % (x0,n0))    
  else:
    print('No hay raíz :(')
  
  # Raíz 2
  x1,n1 = objN.NewtonRaphsonUpperGrade(f,2, tol, maxIter) # Aplicamos la función
  if (x1 != np.inf):
    print('X1 = %f alcanzada en %d iteraciones :D' % (x1,n1))
  else:
    print('No hay raíz :(')

  # Raíz 3
  x2,n2 = objN.NewtonRaphsonUpperGrade(f,0, tol, maxIter) # Aplicamos la función
  if (x2 != np.inf):
    print('X2 = %f alcanzada en %d iteraciones :D' % (x2,n2))    
  else:
    print('No hay raíz :(')
  
  # Raíz 4
  x3,n3 = objN.NewtonRaphsonUpperGrade(f,-2, tol, maxIter) # Aplicamos la función
  if (x3 != np.inf):
    print('X3 = %f alcanzada en %d iteraciones :D' % (x3,n3))
  else:
    print('No hay raíz :(')

if __name__ == "__main__":
  main()

X0 = 3.782459 alcanzada en 944 iteraciones :D
X1 = -1.782459 alcanzada en 1666 iteraciones :D
X2 = -1.782459 alcanzada en 896 iteraciones :D
X3 = -1.782459 alcanzada en 639 iteraciones :D


In [ ]:
from numpy.lib.polynomial import roots
import sympy 
c = [1, -4, -2, 12, -5]
npRoots = np.roots(c)
print('Raíces según Numpy:\n', npRoots)


Raíces según Numpy:
 [ 3.7823834  -1.7823834   1.50827415  0.49172585]
