<a href="https://colab.research.google.com/github/JBSspc/PracticasComputacionII/blob/main/Practica1_MatInv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import sys

class GaussJordan:
  # Método de Gauss Jordan
  def GJ(self, v, c, z):
    v = int(input('Número de ecuaciones: '))
    c = v + 1
    z = np.zeros((v, v + 1))
    x = np.zeros((v, 1))

    print('\nCoeficientes de la matriz aumentada: ')
    for i in range(v):
      for j in range(v + 1):
        z [i][j] = float(input('Valor elemento [' + str(i) +'][' + str(j) + ']: '))

    for i in range(v):
      if z[i][j] == 0.0:
        sys.exit('Alto! Divides entre 0!')
      for j in range(v):
        if i != j:
          r = z[j][i] / z[i][i]
          for k in range(v + 1):
            z[j][k] = z[j][k] - r * z[i][k]
      print("\n", z, "\n")

   # Para la solución
    for i in range (v):
      x[i] = z[i][v] / z[i][i]

    # Mostrar la solución en consola
    print('\nSolución: \n')
    for i in range(v):
      print('X%d = %0.2f' %(i, x[i]), end = '\t')
    return z

def calcMatxInv(v, c, z, objG):
  I = np.identity(v) # Matriz identidad usando numpy

  c = c + v # Ahora tenemos más columnas por agregar la matriz I
  augM = np.concatenate([z, I], axis = 1)
  objG.GJ(v,c, augM)
  print("\n", augM)
  print("\nMatriz Inversa: \n")  
  zInv = np.zeros_like(I)
  for i in range(v):
    zInv[i] = augM[i][c - v: c]
    print(augM[i][c - v: c])
  return zInv
    

def main():

  v = int(input('Número de ecuaciones: '))
  c = v + 1
  z = np.zeros((v, v + 1))
  I = np.identity(v)
   
  #POO
  objG = GaussJordan()
  calcMatxInv(v, c, z, objG)
  





if __name__ == "__main__":
  main()


Número de ecuaciones: 2
Número de ecuaciones: 2

Coeficientes de la matriz aumentada: 
Valor elemento [0][0]: 2
Valor elemento [0][1]: 3
Valor elemento [0][2]: 50
Valor elemento [1][0]: 2
Valor elemento [1][1]: 2
Valor elemento [1][2]: 40

 [[  2.   3.  50.]
 [  0.  -1. -10.]] 


 [[  2.   0.  20.]
 [  0.  -1. -10.]] 


Solución: 

X0 = 10.00	X1 = 10.00	
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matriz Inversa: 

[1. 0.]
[0. 1.]
