<a href="https://colab.research.google.com/github/JBSspc/PracticasComputacionII/blob/main/SistemasEcAlgLineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computación II**
UNAM - ENES J</br>
*Sofía Palacios Cuevas*

## **Sistemas de Ecuaciones Algebráicas Lineales (SEAL)**
* Eliminación Gaussiana (eG)
* Eliminación de Gauss-Jordan (eGJ)
* Determinantes a partir de eG (DeG)
* Matriz Inverza (I)
* Regla de Crammer (Cr)

### **Antes de empezar...**
* Llenar la matriz
* Utilizaremos la matriz: </br>
  <code>
        [[ 1.  -3.  12.  10.],</br>
         [ 5. -12.   2. -33.],</br>
         [ 1. -14. 0. -103.]]
  </code> </br>
  propuesta por Chapra y Canale (1988), p. 277, ejercicio 8.13

In [36]:
# Importamos la librería NumPy
import numpy as np
# Importamos sys para salir del programa cuando se divida entre 0
import sys

# Pedimos al usuario que ingrese el número de variables
v = int(input('Número de ecuaciones: '))

# Hacemos un arreglo (matriz) de v x v + 1
# v + 1 --> # columnas = # variables + 1 (columna de solución)
# La inicializamos en 0 con np.zeros
z = np.zeros((v,v + 1))

# Hacemos un arrglo para la solución
# Tamaño: n x 1 (para que sea vector columna) #no salió :(
# Lo inicializamos en 0
x = np.zeros((v , 1))

# Pedimos al usuario los coef. de la matriz aumentada
print('\nCoeficientes de la matriz aumentada: ')
for i in range(v):
  for j in range(v + 1):
    z [i][j] = float(input('Valor elemento [' + str(i) +'][' + str(j) + ']: '))

print('\nMatriz Z:\n', z, '\n')

Número de ecuaciones: 3

Coeficientes de la matriz aumentada: 
Valor elemento [0][0]: 1
Valor elemento [0][1]: -3
Valor elemento [0][2]: 12
Valor elemento [0][3]: 10
Valor elemento [1][0]: 5
Valor elemento [1][1]: -12
Valor elemento [1][2]: 2
Valor elemento [1][3]: -33
Valor elemento [2][0]: 1
Valor elemento [2][1]: -14
Valor elemento [2][2]: 0
Valor elemento [2][3]: -103

Matriz Z:
 [[   1.   -3.   12.   10.]
 [   5.  -12.    2.  -33.]
 [   1.  -14.    0. -103.]] 



### **Eliminación Gaussiana (eG)**
1. Intercambiar filas (pivoteo parcial)
2. Multiplicar los elementos de una fila por un escalar diferente de cero
3. Restar el producto de una fila por un escalar a otra fila

4. Dividir los la columna de resultados <code>z[i][v]</code> entre los elementos de la diagonal principal <code>A[i][i]</code>

In [21]:
# Método de Gauss 
for i in range(v):
  if z[i][j] == 0.0:
    sys.exit('Alto! Divides entre 0!')
  for j in range(v):
    if i != j:
      r = z[j][i] / z[i][i] # pivote
      for k in range(v + 1):
        z[j][k] = z[j][k] - r * z[i][k]
  # print("\n", z, "\n")

# Para la solución9
for i in range (v): 
  x[i] = z[i][v] / z[i][i] # elemento de la columna de resultados / elemento
                           # a[i][i] de la fila correspondiente

print('Aplicando eG:\n', z)

# Mostrar la solución en consola
print('\nSolución: ')
for i in range(v):
  print('X%d = %0.3f' %(i, x[i]), end = '\t')

# %0.2f -> imprimir float con 2 espacios después del punto -> 0.00


Aplicando eG:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  1.24480712e+01]
 [ 0.00000000e+00  3.00000000e+00  7.10542736e-15  2.47388724e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.24666667e+02 -4.17333333e+02]]

Solución: 
X0 = 12.448	X1 = 8.246	X2 = 1.858	

### **Eliminación de Gauss-Jordan (eGJ)**
* Eliminación Gaussiana (ceros debajo de la diagonal principal)
* Eliminación de GJ (ceros arriba de la diagonal principal)

In [22]:
# Gauss Jordan (ceros arriba de la diagonal principal)
for i in range(v):
  p = z[v-1-i][v-1-i]
  z[v-1-i] = z[v-1-i]/p
  for j in range(v-1-i):
    z[j] = z[j] - z[j][v-1-i] * z[v-1-i] 

for i in range (v): 
  x[i] = z[i][v] / z[i][i]

print('\nAplicando eGJ:\n', z)

# Mostrar la solución en consola
print('\nSolución: ')
for i in range(v):
  print('X%d = %0.3f' %(i, x[i]), end = '\t')




Aplicando eGJ:
 [[ 1.          0.          0.         12.44807122]
 [ 0.          1.          0.          8.2462908 ]
 [-0.         -0.          1.          1.85756677]]

Solución: 
X0 = 12.448	X1 = 8.246	X2 = 1.858	

### **Matriz Inversa (I)**
* Quitamos la columna de resultados
* Agregamos la matriz identidad
* Aplicamos eGJ a ambas matrices de forma paralela
* Hacemos producto punto entre la inversa de nuestra atriz original y la columna de resultados
</br>

Nota 0: Ejecutar después de llenar matriz y antes de eG y GJ. </br>
Nota 1: Copiamos el algoritmo de eG y GJ sin la parte donde se imprime la solución (para evitar conflictos)

In [37]:
I = np.identity(v) # matriz identidad de dimensiones v x v
zc = z[:]
zc = np.delete(z, v, axis = 1)
zI = np.concatenate([zc,I], axis = 1) # axis = 1 -> concatenar columnas
print('\nMatriz A e I concatenadas: \n', zI)


f = len(zI)
s = 2 * len(zI) 
print('\nfilas de zI: ', f, '\ncolumnas de zI: ', s, '\n')



Matriz A e I concatenadas: 
 [[  1.  -3.  12.   1.   0.   0.]
 [  5. -12.   2.   0.   1.   0.]
 [  1. -14.   0.   0.   0.   1.]]

filas de zI:  3 
columnas de zI:  6 



In [38]:
f = len(zI)
s = 2 * len(zI) 
print('\nfilas de zI: ', f, '\ncolumnas de zI: ', s, '\n')

# Gauss (ceros debajo de la diagonal principal)
for i in range(f):
  if zI[i][j] == 0.0:
    sys.exit('Alto! Disión entre 0!')
  for j in range (f):
    if i != j:
      r = zI[j][i] / zI[i][i]
      for k in range(s):
        zI[j][k] = zI[j][k] - r * zI[i][k]

print('Aplicando eliminación Gaussiana (hacia abajo):\n', zI)

# Gauss Jordan (ceros arriba de la diagonal principal)
for i in range(f):
  p = zI[f-1-i][f-1-i]
  zI[f-1-i] = zI[f-1-i]/p
  for j in range(f-1-i):
    zI[j] = zI[j] - zI[j][f-1-i] * zI[f-1-i] 

print('\nAplicando GJ (hacia arriba):\n', zI)

I,AI = np.hsplit(zI,2)
AdotAI = np.dot(zc,AI)

for i in range (v):
  b = z[i][v]
  print(b)

x = np.dot(AI,b)

print(x)


filas de zI:  3 
columnas de zI:  6 

Aplicando eliminación Gaussiana (hacia abajo):
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -4.15430267e-02
   2.49258160e-01 -2.04747774e-01]
 [ 0.00000000e+00  3.00000000e+00  7.10542736e-15 -8.90207715e-03
   5.34124629e-02 -2.58160237e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.24666667e+02 -1.93333333e+01
   3.66666667e+00  1.00000000e+00]]

Aplicando GJ (hacia arriba):
 [[ 1.          0.          0.         -0.04154303  0.24925816 -0.20474777]
 [ 0.          1.          0.         -0.00296736  0.01780415 -0.08605341]
 [-0.         -0.          1.          0.08605341 -0.01632047 -0.00445104]]
10.0
-33.0
-103.0
[[  4.27893175 -25.6735905   21.08902077]
 [  0.30563798  -1.83382789   8.86350148]
 [ -8.86350148   1.6810089    0.45845697]]


### **Determinante (DeG)**
Calcularemos el determinante de una matriz haciendo uso de la eleiminación Gaussiana.
* Realizar eliminaión Gaussiana
* Multiplicar los elementos de la diagonal principal </br>

Ejecutar después de eG

In [9]:
product = 1.0
for i in range(v):
  product *= z[i][i]

print("det(z): ", product)

det(z):  -674.0


Calulando el determinante de una matriz <code>3x3</code> sin utilizar eG.
* Generar una matriz menor 2x2 de la matriz original de 3x3 (misma propuesta por Chapra y Canale)
* Calcular el determinante de la matriz menor

In [2]:
import numpy as np

def Det2x2(M):
    det = -1
    if(len(M) == 2 and len(M[0]) == 2):
        det = (M[0][0] * M[1][1]) - (M[0][1]*M[1][0])
    else:
        print("Not a 2x2 matrix :(")
        exit(0)

    return det

def MenorMat(arr,i,j):
    c = arr[:]
    c = np.delete(c, (i),axis=0)
    return [np.delete(row, (j),axis=0) for row in (c)]

def Det3X3(z):
    det = 0
    if(len(z) == 3 and len(z[0]) == 3):
        for i in range(len(z)):
            a = z[0][i];
            mMenor = MenorMat(z, 0, i)
            #print("Matriz menor:\n", mMenor)
            if i % 2 == 0: # module -> to know signs
                det += a * Det2x2(mMenor) # Indice par --> (+)
            else: # Indice impar --> (-)
                det -= a* Det2x2(mMenor)
    else:
        print("La matriz no es de 3x3")
        exit(0)

    return det

def main():
  # Generate a 3x3 matrix, get it's det
  # M2 = np.random.randint(0, 10,(3,3))

  v = 3

  z = np.zeros((v,v))

  # Pedimos al usuario los coef. de la matriz aumentada
  print('\nCoeficientes de la matriz aumentada: ')
  for i in range(v):
    for j in range(v):
      z [i][j] = float(input('Valor elemento [' + str(i) +'][' + str(j) + ']: '))

  print('\nMatriz Z:\n', z, '\n')

  print("Matriz 3x3\n", z)
  
  print("El determinante de la matriz \n", z, " es:", Det3X3(z))




if __name__ == "__main__":
    main()
  


Coeficientes de la matriz aumentada: 
Valor elemento [0][0]: 1
Valor elemento [0][1]: -3
Valor elemento [0][2]: 12
Valor elemento [1][0]: 5
Valor elemento [1][1]: -12
Valor elemento [1][2]: 2
Valor elemento [2][0]: 1
Valor elemento [2][1]: -14
Valor elemento [2][2]: 0

Matriz Z:
 [[  1.  -3.  12.]
 [  5. -12.   2.]
 [  1. -14.   0.]] 

Matriz 3x3
 [[  1.  -3.  12.]
 [  5. -12.   2.]
 [  1. -14.   0.]]
El determinante de la matriz 
 [[  1.  -3.  12.]
 [  5. -12.   2.]
 [  1. -14.   0.]]  es: -674.0


### **Regla de Cramer (Cr)**
* Obtener el determinante de la matriz, que será el det(Denominador)
* Aislar la columna de resultados
* Sustituir la columna de resultados en la columna de la incógnita actual
* Encontral el determinante del numerador
* Dividir det(Numerador) / det(Denominador)

In [ ]:
print('Columna de resultados: \n')
for i in range(len(z)):
  b = np.zeros(len(z))
  b = z[i][v]
  print(b)

print()






Columna de resultados: 

50.0
40.0



### **Referencias**
* <https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/>


### ⛔ **Bloopers** ⛔ 🐛

In [12]:
import numpy as np
class Det:
  def matrizCoef(self, z,v):
    c = z[:]
    c = np.delete(c, v, axis = 1)
    print('Matriz de coeficientes: \n', c, '\n')

  def det2x2(self, c):
    det = 1
    if (len(c)) == 2 and len(c[0] == 2):
      det = (c[0][0] * c[1][1] - (c[0][1] * c[1][0]) )
    else:
      print('No es una matriz cuadrada :(')
      exit(0)

    return det

  def matMenor(self, c, i, j):
    m = c[:]
    m = np.delete(m, (i), axis = 0)
    return [np.delete(row, (j), axis = 0) for row in (c)]

  def det3x3(self, c):
    det = 0
    
    if(len(c) == 3 and len(c[0]) == 3):
      for i in range(len(c)):
        a = c[0][i]
        mMenor = self.matMenor(c,0,i)
        if i % 2 == 0:
          det += a * self.det2x2(mMenor)
        else:
          det -= a * self.det2x2(mMenor)
    else:
      print('La matriz no tiene dimensiones de 3x3 :(')
      exit(0)
    return det

def main():
  import numpy as np
  # Importamos sys para salir del programa cuando se divida entre 0
  import sys

  # Pedimos al usuario que ingrese el número de variables
  v = int(input('Número de ecuaciones: '))

  # Hacemos un arreglo (matriz) de v x v + 1
  # v + 1 --> # columnas = # variables + 1 (columna de solución)
  # La inicializamos en 0 con np.zeros
  z = np.zeros((v,v + 1))

  # Hacemos un arrglo para la solución
  # Tamaño: n x 1 (para que sea vector columna) #no salió :(
  # Lo inicializamos en 0
  x = np.zeros((v , 1))

  # Pedimos al usuario los coef. de la matriz aumentada
  print('\nCoeficientes de la matriz aumentada: ')
  for i in range(v):
    for j in range(v + 1):
      z [i][j] = float(input('Valor elemento [' + str(i) +'][' + str(j) + ']: '))

  print('\nMatriz Z:\n', z, '\n')
  c = z[:]
  c = np.delete(c, v, axis = 1)
  print('Matriz de coeficientes: \n', c, '\n')
  
  objD = Det()

  objD.det3x3(c)

if __name__ == "__main__":
  main()


Número de ecuaciones: 3

Coeficientes de la matriz aumentada: 
Valor elemento [0][0]: 0
Valor elemento [0][1]: 1
Valor elemento [0][2]: 2
Valor elemento [0][3]: 3
Valor elemento [1][0]: 10
Valor elemento [1][1]: 11
Valor elemento [1][2]: 12
Valor elemento [1][3]: 13
Valor elemento [2][0]: 20
Valor elemento [2][1]: 21
Valor elemento [2][2]: 22
Valor elemento [2][3]: 23

Matriz Z:
 [[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]] 

Matriz de coeficientes: 
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]] 

No es una matriz cuadrada :(
No es una matriz cuadrada :(
No es una matriz cuadrada :(
